services:
  frontend:
    build: 
      context: frontend
    container_name: frontend
    image: blaqkulture/frontend
    ports: 
    - "3000:3000"

  api:
    build:
      context: api
    container_name: backend
    image: blaqkulture/backend
    ports:
    - "9000:9000"